export enum ServerAPI {
  Login = '/v1/auth/login',

  GetEmployeesLst = '/v1/employees/getList',
  GetEmployeeByID = '/v1/employees/',
  StoreEmployee = '/v1/employees/store',
  GetClaimsLst = '/v1/claims/getList',
  GetClaimByID = '/v1/claims/',
  StoreClaim = '/v1/claims/store',
  GetCustomersLst = '/v1/customers/getList',
  GetCustomerByID = '/v1/customers/',
  StoreCustomer = '/v1/customers/store',
  GetTasksLst = '/v1/tasks/getList',
  GetTaskByID = '/v1/tasks/',
  StoreTask = '/v1/tasks/store',

  GetListPositions = '/v1/lists/positions',
  GetListEmployees = '/v1/lists/employees',
  GetListCustomers = '/v1/lists/customers',
  GetListFreedomTypes = '/v1/lists/freedomTypes',
  GetListServices = '/v1/lists/services',
  GetListClaimStates = '/v1/lists/claimStates',
  GetListTaskStates = '/v1/lists/taskStates',
  GetListLevelAccesses = '/v1/lists/levelAccesses',
}
